### ISSUE TITLE
Bug report: after running `wd show` PWD environment variable is changed and impacts other zsh plugins that need it

### ISSUE THREAD

**Issue by kelbyers** [mfaerevaag/wd#114]
**Describe the bug**
My zsh theme is `spaceship-prompt/spaceship-prompt`. That theme includes the current directory in the prompt. Running `wd show` causes the prompt to show an incorrect value. Changing directories will regenerate the prompt with the correct value, but other commands do not cause the prompt to rebuild. Attempting to `cd $PWD` fails, but `cd ; cd -` works. Apparently, the value of `PWD` gets messed up by `wd show` and other things that rely on it fail.

As a side note, I have the latest version of `wd` installed, but `wd --version` shows `wd version 0.5.0`

**To Reproduce**
1. install the spaceship-prompt theme from https://github.com/spaceship-prompt/spaceship-prompt and make sure it is activated
3. cd into any sub-directory from your home directory
4. run `wd show`
5. run `cd $PWD`

**Expected behavior**
The `cd $PWD` command should succeed.

**Screenshots**

```
~ at C02W11Y6HTD6MBP
➜ cd git

~/git at C02W11Y6HTD6MBP
➜ echo $PWD
/Users/jxb2016/git

~/git at C02W11Y6HTD6MBP
➜ wd show
 * No warp point to ~/git

~/git at C02W11Y6HTD6MBP
➜ echo $PWD
~/git

~/git at C02W11Y6HTD6MBP
➜ cd $PWD
cd: no such file or directory: ~/git

~/git at C02W11Y6HTD6MBP
✘1 ➜ cd ; cd -
~/git

~/git at C02W11Y6HTD6MBP
➜ echo $PWD
/Users/jxb2016/git
```

**Desktop (please complete the following information):**
 - zsh version: `zsh 5.9 (x86_64-apple-darwin21.3.0)`
 - wd version: 0.5.2 (maybe, it is the current master branch as of 2 November 2022)

**Comment by alpha-tango-kilo** [comment]
I've pushed [a new branch](https://github.com/mfaerevaag/wd/tree/unclobber-pwd) for you which may fix the issue - would you be able to try it and see for me please? Not currently using zsh (or even Linux) so I don't have a quick way of making sure this works

If it doesn't work and you know a fix that will, I'd happily accept a PR for this. I don't think `wd` should be clobbering environment variables that it itself hasn't created

**Comment by p1r473** [comment]
@kelbyers bump, can you test the new branch please?

**Comment by kelbyers** [comment]
> @kelbyers bump, can you test the new branch please?

I'll take a look at it when I get back to the office in a few days.

**Comment by kelbyers** [comment]
Sorry that it has taken me so long. I forgot about this. The problem still seems to be present. I am no longer using the spaceship them, but I am using a prompt called starship

```
V6YNJVV4QCMBP in ~
❯ cd git

V6YNJVV4QCMBP in ~/git
❯ echo $PWD
/Users/jxb2016/git

V6YNJVV4QCMBP in ~/git
❯ wd show
 * No warp point to ~/git

V6YNJVV4QCMBP in ~/git
❯ echo $PWD
~/git

V6YNJVV4QCMBP in ~/git
❯ cd $PWD
cd: no such file or directory: ~/git

V6YNJVV4QCMBP in ~/git
❌1 ❯ cd

V6YNJVV4QCMBP in ~
❯ cd -
~/git

V6YNJVV4QCMBP in ~/git
❯ echo $PWD
/Users/jxb2016/git
```

**Comment by kelbyers** [comment]
My guess is that this is an issue:

https://github.com/mfaerevaag/wd/blob/c3883c602c10a18e1919d8d4a060a652ef333e71/wd.sh#L361

In ZSH at least, PWD is an automatic parameter. The manual describes it as

> The present working directory. This is set when the shell initializes and whenever the directory changes.

My assumption is that undefined behavior occurs if something other than the shell modifies it.

`wd_show` appears to be the only place in the code that assigns a value to PWD, and it appears to only do so for the purpose of how it checks and displays the saved points. I would think it would be pretty simple to change the variable used in that function to have a different name.

**Comment by alpha-tango-kilo** [comment]
Hey @kelbyers, thanks for getting back to us and confirming the issue is still present.

Could you try the branch I created which undoes our changes to the PWD variables after we're done with it? The branch name is `unclobber-pwd`, and you can see the patch I wrote here: https://github.com/mfaerevaag/wd/commit/4571b2f9089899f68d876c9e49efc092ebbdc120

Alternatively if you want to submit a PR to fix this yourself, be my guest, I'd be happy to review & merge it!

**Comment by kelbyers** [comment]
@alpha-tango-kilo I couldn't get that branch to work for me. I submitted a PR with code that does work for me.

```
❯ wd list
 * All warp points:
control-deploy  ->  ~/git/ose-automation-puppet/control-deploy
          dope  ->  ~/git/one-thd/dope
       ls-base  ->  ~/git/one-thd/locksmith

V6YNJVV4QCMBP in ~/git
❯ wd dope

V6YNJVV4QCMBP in git/one-thd/dope
❯ wd show
 * 1 warp point(s) to current directory: dope

V6YNJVV4QCMBP in git/one-thd/dope
❯ cd ..

V6YNJVV4QCMBP in ~/git/one-thd
❯ wd show
 * No warp point to ~/git/one-thd

V6YNJVV4QCMBP in ~/git/one-thd
❯ echo $PWD
/Users/jxb2016/git/one-thd
```

**Comment by alpha-tango-kilo** [comment]
Thanks for the PR! Merged and released as v0.9.1 🚀 

Always satisfying to close an issue that's well over a year old 😌
